# Generated by Django 5.2.11 on 2026-04-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_contact_number_user_department_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
