# Generated by Django 6.0.4 on 2026-04-19 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_date_joined_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='board',
        ),
        migrations.RemoveField(
            model_name='dailystreak',
            name='student',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='session',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='specialization',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='user',
        ),
        migrations.RemoveField(
            model_name='speechcontext',
            name='educator',
        ),
        migrations.RemoveField(
            model_name='speechsettings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='educator',
        ),
        migrations.AlterModelOptions(
            name='board',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grade_handled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='room_section',
        ),
        migrations.AddField(
            model_name='board',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(default='Untitled Board', max_length=150),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=50)),
                ('disabilities', models.TextField(blank=True, help_text='Details about specific disabilities or needs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='api.teacherprofile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AppSettings',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='DailyStreak',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='SpeechContext',
        ),
        migrations.DeleteModel(
            name='SpeechSettings',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='board',
            name='educator',
        ),
        migrations.RemoveField(
            model_name='board',
            name='name',
        ),
        migrations.RemoveField(
            model_name='board',
            name='status',
        ),
        migrations.RemoveField(
            model_name='board',
            name='updated_at',
        ),
    ]
