# Generated by Django 6.0.4 on 2026-04-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_full_name_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='specialty',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='grade_handled',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='room_section',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
